config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount Sidekiq::Web => '/sidekiq'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :users, only: %i[index destroy]
  resources :daily_records, only: [:index]

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/daily_record.rb
class DailyRecord < ApplicationRecord
  validates :date, presence: true
  validates :male_count, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :female_count, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :male_avg_age, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :female_avg_age, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  after_save :calculate_avg_ages, if: -> { saved_change_to_male_count? || saved_change_to_female_count? }

  class << self
    def upsert(attributes, date)
      daily_record = find_or_initialize_by(date:)
      daily_record.update!(attributes)
    end
  end

  private

  def calculate_avg_ages
    male_avg_age, female_avg_age = User.fetch_gender_avg_ages
    self.male_avg_age = male_avg_age
    self.female_avg_age = female_avg_age
    save
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :uuid, presence: true
  validates :gender, inclusion: { in: %w[male female] }
  validates :age, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  after_destroy :update_daily_record

  def full_name
    "#{name['title']}. #{name['first']} #{name['last']}"
  end

  class << self
    def fetch_gender_avg_ages
      gender_avg_ages = group(:gender).average(:age)
      [gender_avg_ages['male'].to_i, gender_avg_ages['female'].to_i]
    end

    def fetch_count_genders
      gender_count = group(:gender).count
      [gender_count['male'] || 0, gender_count['female'] || 0]
    end

    def upsert(attributes)
      user = find_or_initialize_by(uuid: attributes[:uuid])
      user.update!(attributes)
    end
  end

  private

  def update_daily_record
    DailyRecordUpdateJob.perform_async
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/daily_records_controller.rb
class DailyRecordsController < ApplicationController
  def index
    @daily_records = DailyRecord.all.order(date: :desc).page(params[:page]).per(10)
    daily_records_drop = @daily_records.map { |dr| DailyRecordDrop.new(dr) }
    daily_records_table_liquid_file = File.read(Rails.root.join('app', 'templates', 'daily_records', 'table.liquid'))
    start_number = (@daily_records.current_page - 1) * @daily_records.limit_value
    @daily_records_table_liquid_template = Liquid::Template.parse(daily_records_table_liquid_file).render(
      'daily_records' => daily_records_drop,
      'start_number' => start_number
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = if params[:search].present?
      User.where("COALESCE(name->>'first', '') || ' ' || COALESCE(name->>'last', '') ILIKE ?", "%#{params[:search]}%")
    else
      User.all
    end
    @users = @users.order(created_at: :desc).page(params[:page]).per(10)
    users_drop = @users.map { |user| UserDrop.new(user) }
    users_table_liquid_file = File.read(Rails.root.join('app', 'templates', 'users', 'table.liquid'))
    start_number = (@users.current_page - 1) * @users.limit_value
    @users_table_liquid_template = Liquid::Template.parse(users_table_liquid_file).render(
      'users' => users_drop,
      'form_authenticity_token' => form_authenticity_token,
      'start_number' => start_number
    )
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/daily_records/index.html.erb
<div class='container flex-direction-column m-30'>
  <h1>Daily Records</h1>

  <%= @daily_records_table_liquid_template.html_safe %>

  <div class="pagination">
    <%= paginate @daily_records %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeasyAiAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div class="container">
    <ul class="nav-links">
      <li><%= link_to "Users", users_path %></li>
      <li><%= link_to "Daily Records", daily_records_path %></li>
    </ul>
  </div>
</nav>

app/views/users/index.html.erb
<div class='container flex-direction-column m-30'>
  <h1>Users</h1>

  <%= form_with(url: users_path, method: "get") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search users..." %>
    <%= submit_tag "Search" %>
  <% end %>

  <%= @users_table_liquid_template.html_safe %>

  Total Users: <%= @users.total_count %>

  <div class="pagination">
    <%= paginate @users %>
  </div>
</div>